version: "3.7"



services:

    demo-angular-app:

  

        container_name: demo-appcontainer

        build:

            context: .

            dockerfile: demo-app/dockerfile

        volumes:

            - '.:/app'

            - '/app/node_modules'

        ports:

            - '4201:4200'
