#base image
FROM node:12-alpine as build-step


#install chrome for testing
#RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
#RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
#RUN apt-get update && apt-get install -yq google-chrome-stable

#set working directory
RUN mkdir -p /app
WORKDIR /app

#add node_modules
ENV PATH /app/node_modules/.bin:$PATH

COPY demo-app/package.json /app/package.json
RUN npm install
RUN npm install -g @angular/cli --unsafe


#add app
COPY . /app

#CMD ng serve --host 0.0.0.0

#generate build
RUN cd /app
RUN ng build --prod
#RUN npm run build --prod

#nginx

#base image
FROM nginx:1.16.0-alpine

#copy the artifacts
COPY --from=build-step /app/dist/demo-app /usr/share/nginx/html

EXPOSE 80

CMD ["nginx","-g", "daemon off;"]
